# Database configuration details to connect and evaluate performance

ssh:
  host: "10.196.240.116"
  #host: "ec2-13-49-46-195.eu-north-1.compute.amazonaws.com"
  username: "ubuntu"
  key_path: "/Users/sharminalina/.ssh/id_rsa"
  #key_path: "/Users/sharminalina/desktop/oslomet/thesis/key_AWS/thesis_test.pem"     ## for Creating docker image
database:
  db_type: "mysql"
  #db_type: "postgresql"
  #host: "127.0.0.1"
  host: "10.196.240.116"
  port: "3306"
  #port: "5432"
  db_name: "sysbench"
  username: "root"
  #db_name: "postgres"
  #username: "postgres"
  password: "123"
  driver_name: "mysql"
  #driver_name: "pgsql"
  threads: "10"
  duration: "60"
Load_balance:
  url: "http://10.196.240.116/"
  num_requests: "12000"
  concurrency: "13"
  test_duration: "60"
application:
  host: "10.196.243.48"
  username: "ubuntu"
  key_path: "/Users/sharminalina/.ssh/id_rsa"
  #key_path: "/root/.ssh/id_rsa"  ## For build docker image

plugin_sequence:
  - db_test_plugin
  - loadbalancer_test_plugin
  - application_testing_plugin
  - application_load_testing_plugin
  - plot_dashboard_plugin
  - online_testing_plugin
  

# Prometheus configuration for real-time monitoring
prometheus:
  enabled: true  # Enable or disable Prometheus metrics
  host: "localhost"  # Prometheus server host
  port: 9090  # Prometheus server port
  scrape_interval: "5s"  # How often Prometheus scrapes metrics
  metrics_port: 8000  # Port where your framework exposes metrics
  metrics_path: "/metrics"  # Endpoint where metrics are exposed

alerting:
  email_enabled: true
  email_from: "alerts@yourdomain.com"
  email_to: "team@yourdomain.com"
  smtp_server: "smtp.example.com"
  slack_webhook: "https://hooks.slack.com/services/..."
  
  thresholds:
    cpu_warning: 75
    cpu_critical: 90
    memory_warning: 75
    memory_critical: 90
    http_latency_warning: 500
    http_latency_critical: 1000  

#aws:
 # ssh:
  #  host: "ec2-18-184-137-221.eu-central-1.compute.amazonaws.com"
   # username:  "ubuntu"
    #key_path: "/Users/sharminalina/downloads/sharmina-mac.pem"
  #database:
   # host: "18.184.137.221"
    #port: "3306"
    #db_name: "sysbench"
    #username: "root"
    #password: "123"


